/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 AdamDevenport.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useMediaController from "hooks/useMediaController";
import useFollowCam from "hooks/useFollowCam";
import type { MyGLTF } from "types/mythree";

export function AdamDevenport(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/AdamDevenport.glb"
  ) as MyGLTF;
  const { actions, names, mixer } = useAnimations(animations, group);
  const hipsRef = useRef();
  useMediaController(actions, names, mixer);
  useFollowCam(hipsRef);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AdamDevenportGBAnimations" scale={0.01}>
          <primitive ref={hipsRef} object={nodes.pelvis} />
          <group name="Air_Jordan_3_obj">
            <skinnedMesh
              frustumCulled={false}
              name="Air_Jordan_3_obj_1"
              geometry={nodes.Air_Jordan_3_obj_1.geometry}
              material={materials.Shoe_Left}
              skeleton={nodes.Air_Jordan_3_obj_1.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="Air_Jordan_3_obj_2"
              geometry={nodes.Air_Jordan_3_obj_2.geometry}
              material={materials.Shoe_Right}
              skeleton={nodes.Air_Jordan_3_obj_2.skeleton}
            />
          </group>
          <skinnedMesh
            frustumCulled={false}
            name="Boxers"
            geometry={nodes.Boxers.geometry}
            material={materials.Boxers}
            skeleton={nodes.Boxers.skeleton}
          />
          <group name="CC_Base_Eye">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_1"
              geometry={nodes.CC_Base_Eye_1.geometry}
              material={materials.Std_Eye_R}
              skeleton={nodes.CC_Base_Eye_1.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_2"
              geometry={nodes.CC_Base_Eye_2.geometry}
              material={materials.Std_Cornea_R}
              skeleton={nodes.CC_Base_Eye_2.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_3"
              geometry={nodes.CC_Base_Eye_3.geometry}
              material={materials.Std_Eye_L}
              skeleton={nodes.CC_Base_Eye_3.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Eye_4"
              geometry={nodes.CC_Base_Eye_4.geometry}
              material={materials.Std_Cornea_L}
              skeleton={nodes.CC_Base_Eye_4.skeleton}
            />
          </group>
          <group name="CC_Base_Teeth">
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_1"
              geometry={nodes.CC_Base_Teeth_1.geometry}
              material={materials.Std_Upper_Teeth}
              skeleton={nodes.CC_Base_Teeth_1.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="CC_Base_Teeth_2"
              geometry={nodes.CC_Base_Teeth_2.geometry}
              material={materials.Std_Lower_Teeth}
              skeleton={nodes.CC_Base_Teeth_2.skeleton}
            />
          </group>
          <skinnedMesh
            frustumCulled={false}
            name="Jeans"
            geometry={nodes.Jeans.geometry}
            material={materials.Jeans}
            skeleton={nodes.Jeans.skeleton}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Plaid_Punk_Shirt"
            geometry={nodes.Plaid_Punk_Shirt.geometry}
            material={materials.Plaid_Punk_Shirt}
            skeleton={nodes.Plaid_Punk_Shirt.skeleton}
          />
          <group name="Short_blowback">
            <skinnedMesh
              frustumCulled={false}
              name="Short_blowback_1"
              geometry={nodes.Short_blowback_1.geometry}
              material={materials.Hair_Transparency}
              skeleton={nodes.Short_blowback_1.skeleton}
            />
            <skinnedMesh
              frustumCulled={false}
              name="Short_blowback_2"
              geometry={nodes.Short_blowback_2.geometry}
              material={materials.Scalp_Transparency}
              skeleton={nodes.Short_blowback_2.skeleton}
            />
          </group>
          <skinnedMesh
            frustumCulled={false}
            name="CC_Game_Body"
            geometry={nodes.CC_Game_Body.geometry}
            material={materials.Ga_Skin_Body}
            skeleton={nodes.CC_Game_Body.skeleton}
            morphTargetDictionary={nodes.CC_Game_Body.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Game_Body.morphTargetInfluences}
          />
          <skinnedMesh
            frustumCulled={false}
            name="CC_Game_Tongue"
            geometry={nodes.CC_Game_Tongue.geometry}
            material={materials.Ga_Skin_Body}
            skeleton={nodes.CC_Game_Tongue.skeleton}
            morphTargetDictionary={nodes.CC_Game_Tongue.morphTargetDictionary}
            morphTargetInfluences={nodes.CC_Game_Tongue.morphTargetInfluences}
          />
          <skinnedMesh
            frustumCulled={false}
            name="Chin_Curtain_Sparse"
            geometry={nodes.Chin_Curtain_Sparse.geometry}
            material={materials.Beard_Transparency}
            skeleton={nodes.Chin_Curtain_Sparse.skeleton}
            morphTargetDictionary={
              nodes.Chin_Curtain_Sparse.morphTargetDictionary
            }
            morphTargetInfluences={
              nodes.Chin_Curtain_Sparse.morphTargetInfluences
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/AdamDevenport.glb");
