/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"https://torquetricking.com/3d/AndrewKohrt-SA.glb"
	);
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group scale={0.01}>
				<primitive object={nodes.root} />
				<skinnedMesh
					geometry={nodes.CC_Base_Eye.geometry}
					material={nodes.CC_Base_Eye.material}
					skeleton={nodes.CC_Base_Eye.skeleton}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Teeth.geometry}
					material={nodes.CC_Base_Teeth.material}
					skeleton={nodes.CC_Base_Teeth.skeleton}
				/>
				<skinnedMesh
					geometry={nodes.Object021.geometry}
					material={nodes.Object021.material}
					skeleton={nodes.Object021.skeleton}
				/>
				<skinnedMesh
					geometry={nodes.Tank_Top.geometry}
					material={nodes.Tank_Top.material}
					skeleton={nodes.Tank_Top.skeleton}
				/>
				<skinnedMesh
					geometry={nodes.Warrior_trousers.geometry}
					material={nodes.Warrior_trousers.material}
					skeleton={nodes.Warrior_trousers.skeleton}
				/>
				<skinnedMesh
					name='CC_Base_Body'
					geometry={nodes.CC_Base_Body.geometry}
					material={nodes.CC_Base_Body.material}
					skeleton={nodes.CC_Base_Body.skeleton}
					morphTargetDictionary={nodes.CC_Base_Body.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Base_Body.morphTargetInfluences}
				/>
				<skinnedMesh
					name='CC_Base_Tongue'
					geometry={nodes.CC_Base_Tongue.geometry}
					material={nodes.CC_Base_Tongue.material}
					skeleton={nodes.CC_Base_Tongue.skeleton}
					morphTargetDictionary={nodes.CC_Base_Tongue.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Base_Tongue.morphTargetInfluences}
				/>
				<skinnedMesh
					name='Chin_Curtain_Sparse'
					geometry={nodes.Chin_Curtain_Sparse.geometry}
					material={nodes.Chin_Curtain_Sparse.material}
					skeleton={nodes.Chin_Curtain_Sparse.skeleton}
					morphTargetDictionary={
						nodes.Chin_Curtain_Sparse.morphTargetDictionary
					}
					morphTargetInfluences={
						nodes.Chin_Curtain_Sparse.morphTargetInfluences
					}
				/>
				<skinnedMesh
					name='Mustache_Horseshoe'
					geometry={nodes.Mustache_Horseshoe.geometry}
					material={nodes.Mustache_Horseshoe.material}
					skeleton={nodes.Mustache_Horseshoe.skeleton}
					morphTargetDictionary={nodes.Mustache_Horseshoe.morphTargetDictionary}
					morphTargetInfluences={nodes.Mustache_Horseshoe.morphTargetInfluences}
				/>
				<skinnedMesh
					name='Stubble_Neck'
					geometry={nodes.Stubble_Neck.geometry}
					material={nodes.Stubble_Neck.material}
					skeleton={nodes.Stubble_Neck.skeleton}
					morphTargetDictionary={nodes.Stubble_Neck.morphTargetDictionary}
					morphTargetInfluences={nodes.Stubble_Neck.morphTargetInfluences}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("https://torquetricking.com/AndrewKohrt-SA.glb");
