/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import useMediaController from "../hooks/useMediaController";
import useFollowCam from "../hooks/useFollowCam";
import { MyGLTF } from "types/mythree";

export function KerwoodNew(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/KerwoodNew.glb") as MyGLTF;
  const { actions, names, mixer } = useAnimations(animations, group);
  const hipsRef = useRef();
  useMediaController(actions, names, mixer);
  useFollowCam(hipsRef);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root" scale={0.01}>
          <group
            ref={hipsRef}
            name="Model"
            position={[19.59, 98.79, 13.27]}
            rotation={[1.45, 0.02, 0.58]}
          >
            <primitive object={nodes.CC_Base_Pelvis} />
            <primitive object={nodes.CC_Base_Waist} />
            <skinnedMesh
              ref={hipsRef}
              name="remesh"
              geometry={nodes.remesh.geometry}
              material={materials.remesh_6_combined_Bake}
              skeleton={nodes.remesh.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("/KerwoodNew.glb");
