/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as SwampModel from "../animations/swamp.glb";
export default function Swamp({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF(SwampModel);
	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
				<group
					position={[-2328.63, -550.11, 53.04]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.leaves009.geometry}
						material={materials.American_Beech_leaf}
					/>
					<mesh
						geometry={nodes.trunk013.geometry}
						material={materials["bark3.008"]}
					/>
				</group>
				<group
					position={[-1923.62, -28.59, -33.03]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.leaves010.geometry}
						material={materials["American_Beech_leaf.001"]}
					/>
					<mesh
						geometry={nodes.trunk014.geometry}
						material={materials["bark3.009"]}
					/>
				</group>
				<group
					position={[55.78, -77.32, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={
							nodes.arabian_house_new_detail_window_aFBXASC0463.geometry
						}
						material={materials.trunks_b}
					/>
					<mesh
						geometry={
							nodes.arabian_house_new_detail_window_aFBXASC0464.geometry
						}
						material={materials.doors_windows_b}
					/>
					<mesh
						geometry={
							nodes.arabian_house_new_detail_window_aFBXASC0465.geometry
						}
						material={materials.planks_5}
					/>
				</group>
				<group
					position={[81.14, 198.01, 9.37]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state1FBXASC0460.geometry
						}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state1FBXASC0461.geometry
						}
						material={materials.empire_gatehouse_gate_skinned}
					/>
					<mesh
						geometry={nodes.aserai_castle_gate_inner_l1_plank.geometry}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0460.geometry
						}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0461.geometry
						}
						material={materials.empire_gatehouse_gate_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0462.geometry
						}
						material={materials.floor_2_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state3FBXASC0460.geometry
						}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state3FBXASC0461.geometry
						}
						material={materials.empire_gatehouse_gate_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state4FBXASC0460.geometry
						}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state4FBXASC0461.geometry
						}
						material={materials.empire_gatehouse_gate_skinned}
					/>
					<group position={[0.14, 3.39, -0.26]} rotation={[3.07, -0.5, -0.3]}>
						<mesh
							geometry={nodes.aserai_castle_gate_inner_l1_state5_part1.geometry}
							material={materials.woodsection_b}
						/>
					</group>
					<group position={[1.08, 1.69, -0.03]} rotation={[0.28, -0.05, -0.19]}>
						<mesh
							geometry={nodes.aserai_castle_gate_inner_l1_state5_part2.geometry}
							material={materials["woodsection_b.001"]}
						/>
					</group>
					<group position={[-1.1, 1.39, -0.14]} rotation={[-2.78, 0.55, -0.33]}>
						<mesh
							geometry={nodes.aserai_castle_gate_inner_l1_state5_part3.geometry}
							material={materials.woodsection_b}
						/>
					</group>
					<group position={[-0.11, 2.34, -0.08]} rotation={[2.7, -0.57, 2.37]}>
						<mesh
							geometry={
								nodes.aserai_castle_gate_inner_l1_state5_part2001.geometry
							}
							material={materials["woodsection_b.002"]}
						/>
					</group>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state5FBXASC0460.geometry
						}
						material={materials.woodsection_b_skinned}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state5FBXASC0461.geometry
						}
						material={materials.empire_gatehouse_gate_skinned}
					/>
				</group>
				<group
					position={[147.46, -350.59, 4.44]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state1FBXASC0460001.geometry
						}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state1FBXASC0461001.geometry
						}
						material={materials["empire_gatehouse_gate_skinned.001"]}
					/>
					<mesh
						geometry={nodes.aserai_castle_gate_inner_l1_plank001.geometry}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0460001.geometry
						}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0461001.geometry
						}
						material={materials["empire_gatehouse_gate_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state2FBXASC0462001.geometry
						}
						material={materials["floor_2_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state3FBXASC0460001.geometry
						}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state3FBXASC0461001.geometry
						}
						material={materials["empire_gatehouse_gate_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state4FBXASC0460001.geometry
						}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state4FBXASC0461001.geometry
						}
						material={materials["empire_gatehouse_gate_skinned.001"]}
					/>
					<group position={[0.14, 3.39, -0.26]} rotation={[3.07, -0.5, -0.3]}>
						<mesh
							geometry={
								nodes.aserai_castle_gate_inner_l1_state5_part1001.geometry
							}
							material={materials["woodsection_b.003"]}
						/>
					</group>
					<group position={[1.08, 1.69, -0.03]} rotation={[0.28, -0.05, -0.19]}>
						<mesh
							geometry={
								nodes.aserai_castle_gate_inner_l1_state5_part2002.geometry
							}
							material={materials["woodsection_b.004"]}
						/>
					</group>
					<group position={[-1.1, 1.39, -0.14]} rotation={[-2.78, 0.55, -0.33]}>
						<mesh
							geometry={
								nodes.aserai_castle_gate_inner_l1_state5_part3001.geometry
							}
							material={materials["woodsection_b.003"]}
						/>
					</group>
					<group position={[-0.11, 2.34, -0.08]} rotation={[2.7, -0.57, 2.37]}>
						<mesh
							geometry={
								nodes.aserai_castle_gate_inner_l1_state5_part2003.geometry
							}
							material={materials["woodsection_b.005"]}
						/>
					</group>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state5FBXASC0460001.geometry
						}
						material={materials["woodsection_b_skinned.001"]}
					/>
					<mesh
						geometry={
							nodes.aserai_castle_gate_inner_l1_state5FBXASC0461001.geometry
						}
						material={materials["empire_gatehouse_gate_skinned.001"]}
					/>
				</group>
				<group
					position={[-11.85, 412.15, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_barrel_aFBXASC0463.geometry}
						material={materials.objects_a}
					/>
				</group>
				<group
					position={[57.38, 210.52, -9.37]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_broom_aFBXASC0463.geometry}
						material={materials["objects_a.003"]}
					/>
					<mesh
						geometry={nodes.bd_broom_aFBXASC0465.geometry}
						material={materials.straw_a}
					/>
				</group>
				<group
					position={[-14.08, 474.24, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_bucket_bFBXASC0463.geometry}
						material={materials["objects_a.005"]}
					/>
					<mesh
						geometry={nodes.bd_bucket_bFBXASC0467.geometry}
						material={materials.wat_bucket}
					/>
				</group>
				<group
					position={[-6.16, 405.6, -87.77]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_hammer001.geometry}
						material={materials.merchandise}
					/>
					<mesh
						geometry={nodes.bd_hammerFBXASC0462.geometry}
						material={materials["kitchen.001"]}
					/>
				</group>
				<group
					position={[195.18, 295.9, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0461.geometry}
						material={materials.plank_b}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0463.geometry}
						material={materials.planks_6}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0464.geometry}
						material={materials.planks_4}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0466.geometry}
						material={materials.planks_3}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0467.geometry}
						material={materials.plank_d}
					/>
				</group>
				<group
					position={[195.18, 295.9, -127.91]}
					rotation={[-2.18, -Math.PI / 2, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0461001.geometry}
						material={materials["plank_b.002"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0463001.geometry}
						material={materials["planks_6.003"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0464001.geometry}
						material={materials["planks_4.002"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0466001.geometry}
						material={materials["planks_3.002"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0467001.geometry}
						material={materials["plank_d.002"]}
					/>
				</group>
				<group
					position={[419.73, 295.9, -127.91]}
					rotation={[-2.18, -Math.PI / 2, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0461002.geometry}
						material={materials["plank_b.004"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0463002.geometry}
						material={materials["planks_6.005"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0464002.geometry}
						material={materials["planks_4.004"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0466002.geometry}
						material={materials["planks_3.004"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0467002.geometry}
						material={materials["plank_d.004"]}
					/>
				</group>
				<group
					position={[419.73, 49.08, -127.91]}
					rotation={[-1.31, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0461003.geometry}
						material={materials["plank_b.006"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0463003.geometry}
						material={materials["planks_6.007"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0464003.geometry}
						material={materials["planks_4.006"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0466003.geometry}
						material={materials["planks_3.006"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0467003.geometry}
						material={materials["plank_d.006"]}
					/>
				</group>
				<group
					position={[219.11, 49.08, -127.91]}
					rotation={[-1.31, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0461004.geometry}
						material={materials["plank_b.008"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0463004.geometry}
						material={materials["planks_6.009"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0464004.geometry}
						material={materials["planks_4.008"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0466004.geometry}
						material={materials["planks_3.008"]}
					/>
					<mesh
						geometry={nodes.bd_wood_heap_eFBXASC0467004.geometry}
						material={materials["plank_d.008"]}
					/>
				</group>
				<group
					position={[-920.09, 358.19, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Black_Oak_branch1001.geometry}
						material={materials["TreeBark_7.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1jEI001.geometry}
						material={materials.Shumard_Oak_leaf_Mat2}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1pR3001.geometry}
						material={materials.Shumard_Oak_leaf_v4_Mat2}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1snf001.geometry}
						material={materials.Shumard_Oak_leaf_v3_Mat2}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1m4u001.geometry}
						material={materials.Shumard_Oak_leaf_v2_Mat2}
					/>
					<mesh
						geometry={nodes.Black_Oak_base001.geometry}
						material={materials["TreeBark_7.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch2001.geometry}
						material={materials["TreeBark_7.001"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch3.geometry}
						material={materials.Shumard_Oak_leaf_Mat2}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch4.geometry}
						material={materials.Shumard_Oak_leaf_v3_Mat2}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch5.geometry}
						material={materials.Shumard_Oak_leaf_v4_Mat2}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch6.geometry}
						material={materials.Shumard_Oak_leaf_Mat2}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
				</group>
				<group position={[601.52, 1470.25, 0]} rotation={[-Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.Black_Oak_branch1002.geometry}
						material={materials["TreeBark_7.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1jEI002.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1pR3002.geometry}
						material={materials["Shumard_Oak_leaf_v4_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1snf002.geometry}
						material={materials["Shumard_Oak_leaf_v3_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1m4u002.geometry}
						material={materials["Shumard_Oak_leaf_v2_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_base002.geometry}
						material={materials["TreeBark_7.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch2002.geometry}
						material={materials["TreeBark_7.002"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch3001.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.001"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch4001.geometry}
						material={materials["Shumard_Oak_leaf_v3_Mat2.001"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch5001.geometry}
						material={materials["Shumard_Oak_leaf_v4_Mat2.001"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch6001.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.001"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
				</group>
				<group
					position={[-1920.75, -298.38, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Black_Oak_branch1003.geometry}
						material={materials["TreeBark_7.003"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1jEI003.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1pR3003.geometry}
						material={materials["Shumard_Oak_leaf_v4_Mat2.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1snf003.geometry}
						material={materials["Shumard_Oak_leaf_v3_Mat2.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1m4u003.geometry}
						material={materials["Shumard_Oak_leaf_v2_Mat2.002"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_base003.geometry}
						material={materials["TreeBark_7.003"]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch2003.geometry}
						material={materials["TreeBark_7.003"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch3002.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.002"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch4002.geometry}
						material={materials["Shumard_Oak_leaf_v3_Mat2.002"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch5002.geometry}
						material={materials["Shumard_Oak_leaf_v4_Mat2.002"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch6002.geometry}
						material={materials["Shumard_Oak_leaf_Mat2.002"]}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
				</group>
				<group
					position={[79.87, -837.5, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Black_Oak_branch1.geometry}
						material={materials.TreeBark_7}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1jEI.geometry}
						material={materials.Black_Oak_leaf_Mat}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1m4u.geometry}
						material={materials.Black_Oak_leaf_v2_Mat}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1pR3.geometry}
						material={materials.Black_Oak_leaf_v3_Mat}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch1snf.geometry}
						material={materials.Black_Oak_leaf_v4_Mat}
					/>
					<mesh
						geometry={nodes.Black_Oak_base.geometry}
						material={materials.TreeBark_07}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch2.geometry}
						material={materials.TreeBark_8}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch22M1.geometry}
						material={materials.Black_Oak_leaf_v2_Mat}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch26D9.geometry}
						material={materials.Black_Oak_leaf_v3_Mat}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch29Zm.geometry}
						material={materials.Black_Oak_leaf_v4_Mat}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
					<mesh
						geometry={nodes.Black_Oak_branch2z0P.geometry}
						material={materials.Black_Oak_leaf_Mat}
						position={[71.24, 1210.33, -497.91]}
						rotation={[-0.67, 0.11, -0.46]}
					/>
				</group>
				<group
					position={[-169.12, -431.03, -46.08]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={511.68}>
					<mesh
						geometry={nodes.cauldron001.geometry}
						material={materials.roman_pot}
					/>
				</group>
				<group
					position={[-725.97, -1442.49, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.branches.geometry}
						material={materials.TreeBark_10}
					/>
					<mesh
						geometry={nodes.branchneedles.geometry}
						material={materials.Pine_needles}
					/>
					<mesh
						geometry={nodes.branchsmall.geometry}
						material={materials.TreeBark_10}
					/>
					<mesh
						geometry={nodes.needles.geometry}
						material={materials.Pine_needles}
					/>
					<mesh
						geometry={nodes.single_branch.geometry}
						material={materials.TreeBark_10}
					/>
					<mesh
						geometry={nodes.singneedles.geometry}
						material={materials.Pine_needles}
					/>
					<mesh
						geometry={nodes.Pine_bark_Mat.geometry}
						material={materials.TreeBark_10}
					/>
					<mesh
						geometry={nodes.Pine_needles_Mat.geometry}
						material={materials.Pine_needles}
					/>
					<mesh
						geometry={nodes.trunk004.geometry}
						material={materials.TreeBark_10}
					/>
				</group>
				<group
					position={[-1848.28, -760.31, -37.75]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.leaves011.geometry}
						material={materials["American_Beech_leaf.002"]}
					/>
					<mesh
						geometry={nodes.trunk015.geometry}
						material={materials["bark3.010"]}
					/>
				</group>
				<group
					position={[-149.37, -6.49, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.empire_street_tent_01FBXASC0460.geometry}
						material={materials["objects_a.002"]}
					/>
					<mesh
						geometry={nodes.empire_street_tent_01FBXASC0461.geometry}
						material={materials.empire_street_tents_01_wave}
					/>
				</group>
				<group
					position={[-517.76, -340.35, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1001.geometry}
						material={materials.fallleaves}
					/>
				</group>
				<group
					position={[-1019.58, -278.29, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1002.geometry}
						material={materials["fallleaves.001"]}
					/>
				</group>
				<group
					position={[-576.7, -588.85, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1003.geometry}
						material={materials["fallleaves.006"]}
					/>
				</group>
				<group
					position={[-708.02, 231.52, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1004.geometry}
						material={materials["fallleaves.007"]}
					/>
				</group>
				<group position={[-634.29, 267, 0]} rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1005.geometry}
						material={materials["fallleaves.008"]}
					/>
				</group>
				<group position={[-755.9, 66.2, 0]} rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1006.geometry}
						material={materials["fallleaves.009"]}
					/>
				</group>
				<group
					position={[-425.3, 227.08, -1.22]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1007.geometry}
						material={materials["fallleaves.012"]}
					/>
				</group>
				<group
					position={[-687.32, -293.82, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster1008.geometry}
						material={materials["fallleaves.015"]}
					/>
				</group>
				<group
					position={[-1002.73, -111.04, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster2001.geometry}
						material={materials["fallleaves.002"]}
					/>
				</group>
				<group
					position={[-793.89, 189.21, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster2002.geometry}
						material={materials["fallleaves.010"]}
					/>
				</group>
				<group
					position={[-467.65, 87.94, -3.24]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.fallcluster2003.geometry}
						material={materials["fallleaves.011"]}
					/>
				</group>
				<group
					position={[1108.39, 1283.55, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Fraxinus_branchShape_MASH1_Instancer_0.geometry}
						material={materials.Apple_bark_Mat_2}
					/>
					<mesh
						geometry={nodes.Fraxinus_branchShape_MASH1_Instancer_0jEI.geometry}
						material={materials.Fraxinus_leaves}
					/>
					<mesh
						geometry={nodes.Fraxinus_trunk.geometry}
						material={materials.Apple_bark_Mat}
					/>
				</group>
				<group
					position={[-1961.14, -657.67, -33.4]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.flowers1001.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.stem1001.geometry}
						material={materials.goldenchain_stems}
					/>
					<mesh
						geometry={nodes.buds2001.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.flowers2001.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.stem2001.geometry}
						material={materials.goldenchain_stems}
					/>
					<mesh
						geometry={nodes.leaves012.geometry}
						material={materials.goldenchain_leaves}
					/>
					<mesh
						geometry={nodes.trunk019.geometry}
						material={materials["bark3.014"]}
					/>
					<mesh
						geometry={nodes.flowers1.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.stem1.geometry}
						material={materials.goldenchain_stems}
					/>
					<mesh
						geometry={nodes.buds2.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.flowers2.geometry}
						material={materials.goldenchain_flowers}
					/>
					<mesh
						geometry={nodes.stem2.geometry}
						material={materials.goldenchain_stems}
					/>
				</group>
				<group
					position={[425.93, 2020.52, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.palmbark.geometry}
						material={materials.grasspalmbark_mat}
					/>
					<mesh
						geometry={nodes.palmleaves_1.geometry}
						material={materials.palmleaves1_mat}
					/>
					<mesh
						geometry={nodes.palmleaves_2.geometry}
						material={materials.palmleaves2_mat}
					/>
					<mesh
						geometry={nodes.palmleaves_3.geometry}
						material={materials.palmleaves3_mat}
					/>
					<mesh
						geometry={nodes.palmleaves_4.geometry}
						material={materials.palmleaves4_mat}
					/>
				</group>
				<group
					position={[-64.36, -547.4, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a.geometry}
						material={materials.lawngrass_a_mat}
					/>
				</group>
				<group
					position={[-505.53, -527.95, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a009.geometry}
						material={materials["lawngrass_a_mat.016"]}
						position={[-99.82, 0, 501.89]}
						scale={[3.32, 1.43, 3.32]}
					/>
					<mesh
						geometry={nodes.Grass_short_a_01.geometry}
						material={materials["lawngrass_a_mat.016"]}
						position={[0, 0, 276.85]}
						scale={2.42}
					/>
				</group>
				<group
					position={[-523.38, -678.85, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a010.geometry}
						material={materials["lawngrass_a_mat.017"]}
						position={[-193.27, 0, 307.22]}
					/>
					<mesh
						geometry={nodes.Grass_short_a_01001.geometry}
						material={materials["lawngrass_a_mat.017"]}
						position={[-206.63, 0, 151.24]}
						scale={2.15}
					/>
				</group>
				<group
					position={[-841.39, -1099.79, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={3.79}>
					<mesh
						geometry={nodes.Grass_short_a011.geometry}
						material={materials["lawngrass_a_mat.018"]}
					/>
				</group>
				<group
					position={[-1246.84, -1099.79, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={3.79}>
					<mesh
						geometry={nodes.Grass_short_a012.geometry}
						material={materials["lawngrass_a_mat.019"]}
					/>
				</group>
				<group
					position={[-1570.91, -1099.79, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={3.79}>
					<mesh
						geometry={nodes.Grass_short_a013.geometry}
						material={materials["lawngrass_a_mat.020"]}
					/>
				</group>
				<group
					position={[-466.24, -1099.79, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={3.79}>
					<mesh
						geometry={nodes.Grass_short_a014.geometry}
						material={materials["lawngrass_a_mat.021"]}
					/>
				</group>
				<group
					position={[-142.87, -1099.79, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={3.79}>
					<mesh
						geometry={nodes.Grass_short_a015.geometry}
						material={materials["lawngrass_a_mat.022"]}
					/>
				</group>
				<group
					position={[-1928.98, 145.88, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={4}>
					<mesh
						geometry={nodes.Grass_short_a016.geometry}
						material={materials["lawngrass_a_mat.023"]}
					/>
				</group>
				<group
					position={[-1928.98, -295.27, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={4}>
					<mesh
						geometry={nodes.Grass_short_a017.geometry}
						material={materials["lawngrass_a_mat.024"]}
					/>
				</group>
				<group
					position={[-1928.98, -782.31, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={4}>
					<mesh
						geometry={nodes.Grass_short_a018.geometry}
						material={materials["lawngrass_a_mat.025"]}
					/>
				</group>
				<group
					position={[83.75, -630.52, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a001.geometry}
						material={materials["lawngrass_a_mat.001"]}
					/>
				</group>
				<group
					position={[-1621.62, -459.29, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 1.79, 4]}>
					<mesh
						geometry={nodes.Grass_short_a019.geometry}
						material={materials["lawngrass_a_mat.026"]}
					/>
				</group>
				<group
					position={[-1621.62, -38.61, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 1.79, 4]}>
					<mesh
						geometry={nodes.Grass_short_a020.geometry}
						material={materials["lawngrass_a_mat.027"]}
					/>
				</group>
				<group
					position={[-1621.62, 294.05, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 0.97, 4]}>
					<mesh
						geometry={nodes.Grass_short_a021.geometry}
						material={materials["lawngrass_a_mat.028"]}
					/>
				</group>
				<group
					position={[-1285.41, -196.25, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 0.97, 4]}>
					<mesh
						geometry={nodes.Grass_short_a022.geometry}
						material={materials["lawngrass_a_mat.029"]}
					/>
				</group>
				<group
					position={[-1385.28, -637.62, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 0.97, 4]}>
					<mesh
						geometry={nodes.Grass_short_a023.geometry}
						material={materials["lawngrass_a_mat.030"]}
					/>
				</group>
				<group
					position={[-1285.41, 186, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={[4, 0.97, 4]}>
					<mesh
						geometry={nodes.Grass_short_a024.geometry}
						material={materials["lawngrass_a_mat.031"]}
					/>
				</group>
				<group
					position={[-958.02, 1196.9, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={6.15}>
					<mesh
						geometry={nodes.Grass_short_a025.geometry}
						material={materials["lawngrass_a_mat.032"]}
					/>
				</group>
				<group
					position={[-1575, 804.77, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={6.15}>
					<mesh
						geometry={nodes.Grass_short_a026.geometry}
						material={materials["lawngrass_a_mat.033"]}
					/>
				</group>
				<group
					position={[-37.29, 102.61, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a002.geometry}
						material={materials["lawngrass_a_mat.002"]}
					/>
				</group>
				<group
					position={[-424.32, -583.14, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a003.geometry}
						material={materials["lawngrass_a_mat.003"]}
						position={[-238.94, 0, -145.46]}
						scale={[3.6, 1.46, 3.6]}
					/>
				</group>
				<group position={[68.62, 90.57, 0]} rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a004.geometry}
						material={materials["lawngrass_a_mat.004"]}
					/>
				</group>
				<group
					position={[-52.18, 242.4, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a005.geometry}
						material={materials["lawngrass_a_mat.005"]}
					/>
				</group>
				<group
					position={[64.44, 185.19, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a006.geometry}
						material={materials["lawngrass_a_mat.006"]}
					/>
				</group>
				<group position={[4.97, 299.98, 0]} rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a007.geometry}
						material={materials["lawngrass_a_mat.007"]}
					/>
				</group>
				<group
					position={[-120.06, 194.36, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_short_a008.geometry}
						material={materials["lawngrass_a_mat.008"]}
					/>
				</group>
				<group
					position={[-166.94, 336.42, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_a.geometry}
						material={materials["lawngrass_a_mat.009"]}
					/>
				</group>
				<group
					position={[-97.91, 386.27, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_a001.geometry}
						material={materials["lawngrass_a_mat.010"]}
					/>
				</group>
				<group
					position={[1.46, -739.07, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_a002.geometry}
						material={materials["lawngrass_a_mat.011"]}
					/>
				</group>
				<group
					position={[-772.33, 500.99, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_a003.geometry}
						material={materials["lawngrass_a_mat.012"]}
					/>
				</group>
				<group
					position={[-724.12, 494.43, -20.41]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_a004.geometry}
						material={materials["lawngrass_a_mat.013"]}
					/>
				</group>
				<group
					position={[-701.98, 503.6, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_c.geometry}
						material={materials["lawngrass_a_mat.014"]}
					/>
				</group>
				<group
					position={[-181.26, 246.49, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Grass_trimmed_c001.geometry}
						material={materials["lawngrass_a_mat.015"]}
					/>
				</group>
				<group
					position={[42.95, -494.13, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.flowers.geometry}
						material={materials.HibiscusFlower_Mat}
					/>
					<mesh
						geometry={nodes.leaves.geometry}
						material={materials.Hibiscus_leaf_Mat}
					/>
					<mesh
						geometry={nodes.trunk002.geometry}
						material={materials["bark3.002"]}
					/>
				</group>
				<group
					position={[728.38, 1376.94, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.flowers002.geometry}
						material={materials["HibiscusFlower_Mat.001"]}
					/>
					<mesh
						geometry={nodes.leaves013.geometry}
						material={materials["Hibiscus_leaf_Mat.001"]}
					/>
					<mesh
						geometry={nodes.trunk022.geometry}
						material={materials["bark3.018"]}
					/>
				</group>
				<group
					position={[-159.17, -711.61, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves.geometry}
						material={materials.HollyPrivet_Mat}
					/>
					<mesh geometry={nodes.trunk.geometry} material={materials.bark3} />
				</group>
				<group
					position={[-621.45, 1323.46, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={2.38}>
					<mesh
						geometry={nodes.Leaves009.geometry}
						material={materials["HollyPrivet_Mat.009"]}
					/>
					<mesh
						geometry={nodes.trunk021.geometry}
						material={materials["bark3.016"]}
					/>
				</group>
				<group
					position={[738.16, 523.29, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves011.geometry}
						material={materials["HollyPrivet_Mat.011"]}
					/>
					<mesh
						geometry={nodes.trunk024.geometry}
						material={materials["bark3.021"]}
					/>
				</group>
				<group
					position={[-796.47, 428.75, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves001.geometry}
						material={materials["HollyPrivet_Mat.001"]}
					/>
					<mesh
						geometry={nodes.trunk001.geometry}
						material={materials["bark3.001"]}
					/>
				</group>
				<group
					position={[196.89, 443.72, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves002.geometry}
						material={materials["HollyPrivet_Mat.002"]}
					/>
					<mesh
						geometry={nodes.trunk003.geometry}
						material={materials["bark3.003"]}
					/>
				</group>
				<group
					position={[-873.47, -791.74, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves003.geometry}
						material={materials["HollyPrivet_Mat.003"]}
					/>
					<mesh
						geometry={nodes.trunk007.geometry}
						material={materials["bark3.004"]}
					/>
				</group>
				<group
					position={[-1815.98, -416.03, -26.41]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves005.geometry}
						material={materials["HollyPrivet_Mat.005"]}
					/>
					<mesh
						geometry={nodes.trunk016.geometry}
						material={materials["bark3.011"]}
					/>
				</group>
				<group
					position={[-1912.29, -32.13, -33.41]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves006.geometry}
						material={materials["HollyPrivet_Mat.006"]}
					/>
					<mesh
						geometry={nodes.trunk017.geometry}
						material={materials["bark3.012"]}
					/>
				</group>
				<group
					position={[-1446.16, -1303.94, -19.19]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves007.geometry}
						material={materials["HollyPrivet_Mat.007"]}
					/>
					<mesh
						geometry={nodes.trunk018.geometry}
						material={materials["bark3.013"]}
					/>
				</group>
				<group
					position={[-1315.48, 1162.83, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={2.38}>
					<mesh
						geometry={nodes.Leaves008.geometry}
						material={materials["HollyPrivet_Mat.008"]}
					/>
					<mesh
						geometry={nodes.trunk020.geometry}
						material={materials["bark3.015"]}
					/>
				</group>
				<group
					position={[822.03, 1912.84, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Leaves010.geometry}
						material={materials["HollyPrivet_Mat.010"]}
					/>
					<mesh
						geometry={nodes.trunk023.geometry}
						material={materials["bark3.019"]}
					/>
				</group>
				<group
					position={[-1137.11, -1442.14, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.branch.geometry}
						material={materials.TreeBark_01}
					/>
					<mesh
						geometry={nodes.leaves002.geometry}
						material={materials.HoneyLocust_leaf_Mat1}
					/>
					<mesh
						geometry={nodes.top.geometry}
						material={materials.HoneyLocust_leaf_Mat1}
					/>
					<mesh
						geometry={nodes.trunk005.geometry}
						material={materials.TreeBark_01}
					/>
				</group>
				<group
					position={[-2095.36, -1099.77, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.branch001.geometry}
						material={materials["TreeBark_01.001"]}
					/>
					<mesh
						geometry={nodes.leaves005.geometry}
						material={materials["HoneyLocust_leaf_Mat1.001"]}
					/>
					<mesh
						geometry={nodes.top001.geometry}
						material={materials["HoneyLocust_leaf_Mat1.001"]}
					/>
					<mesh
						geometry={nodes.trunk008.geometry}
						material={materials["TreeBark_01.001"]}
					/>
				</group>
				<group
					position={[-1987.67, 168.18, -7.82]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.flowers001.geometry}
						material={materials.HoneyMyrtle_Mat1}
					/>
					<mesh
						geometry={nodes.leaves008.geometry}
						material={materials.honeymyrtle_leaves}
					/>
					<mesh
						geometry={nodes.trunk012.geometry}
						material={materials["bark3.007"]}
					/>
				</group>
				<group
					position={[414.92, 388.03, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.hut_d001.geometry}
						material={materials["trunks_b.001"]}
					/>
					<mesh
						geometry={nodes.hut_dFBXASC0461.geometry}
						material={materials["planks_6.002"]}
					/>
				</group>
				<group
					position={[-2257.31, 307.05, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={2.38}>
					<mesh
						geometry={nodes.leaves006.geometry}
						material={materials.japaneseflame_leaves}
					/>
					<mesh
						geometry={nodes.trunk009.geometry}
						material={materials.japaneseflame_bark}
					/>
				</group>
				<group
					position={[-1699.41, -282.08, -20.76]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.jungleflame_flowerpedals_0.geometry}
						material={materials.JungleFlame_Flowers}
					/>
					<mesh
						geometry={nodes.bark.geometry}
						material={materials.JungleFlame_bark}
					/>
					<mesh
						geometry={nodes.leaves_v1.geometry}
						material={materials.JungleFlame_Leaves_1}
					/>
					<mesh
						geometry={nodes.leaves_v2.geometry}
						material={materials.JungleFlame_Leaves_2}
					/>
					<mesh
						geometry={nodes.leaves_v3.geometry}
						material={materials.JungleFlame_Leaves_3}
					/>
					<mesh
						geometry={nodes.leaves_v4.geometry}
						material={materials.JungleFlame_Leaves_1}
					/>
					<mesh
						geometry={nodes.jungleflame_flowerpedals.geometry}
						material={materials.JungleFlame_Flowers}
					/>
				</group>
				<group
					position={[426.14, 517.68, -108.11]}
					rotation={[-1.65, 0.03, 0]}
					scale={78}>
					<mesh
						geometry={nodes.kitchen_hanger_bFBXASC0460.geometry}
						material={materials.kitchen}
					/>
					<mesh
						geometry={nodes.kitchen_hanger_bFBXASC0461.geometry}
						material={materials.lights_a}
					/>
				</group>
				<group
					position={[-1404.86, -1402.48, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.leaves003.geometry}
						material={materials.Aspen_leaf_Mat}
					/>
					<mesh
						geometry={nodes.trunk006.geometry}
						material={materials.TreeBark_04}
					/>
				</group>
				<group
					position={[-1729.48, 837.84, -47.67]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Lilac_Branch.geometry}
						material={materials["bark3_2.001"]}
					/>
					<mesh
						geometry={nodes.Lilac_BranchfrA.geometry}
						material={materials.Lilac}
					/>
					<mesh
						geometry={nodes.Lilac_trunk.geometry}
						material={materials["bark3.017"]}
					/>
				</group>
				<group
					position={[-1299.26, -895.81, -8.24]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Lupin_leaves.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.Lupin_stalk.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.LupinFlower.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.lupinleaf1.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.lupinleaf2.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.lupinleaf3.geometry}
						material={materials.Lupin_m}
					/>
					<mesh
						geometry={nodes.lupinleaf4.geometry}
						material={materials.Lupin_m}
					/>
				</group>
				<group
					position={[-602.74, -319.88, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.maplefall1001.geometry}
						material={materials["fallleaves.003"]}
					/>
				</group>
				<group
					position={[74.1, 415.83, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<group position={[0, 0, -0.03]} rotation={[0, 0.81, 0]}>
						<mesh
							geometry={nodes.foods_basket_cFBXASC0462.geometry}
							material={materials.building_detail_new_a}
						/>
					</group>
					<group position={[0.04, 0.59, 0.01]} rotation={[-0.07, -0.44, -0.98]}>
						<mesh
							geometry={nodes.sheep_head.geometry}
							material={materials.food_d}
						/>
					</group>
					<group position={[-0.14, 0.59, 0.07]} rotation={[1.77, 0.68, -1.44]}>
						<mesh
							geometry={nodes.sheep_head001.geometry}
							material={materials["food_d.001"]}
						/>
					</group>
					<group position={[-0.25, 0.56, 0.34]} rotation={[-0.04, 1.07, -1.19]}>
						<mesh
							geometry={nodes.sheep_head010.geometry}
							material={materials["food_d.010"]}
						/>
					</group>
					<group position={[-0.04, 0.55, -0.19]} rotation={[0, 0, -1.38]}>
						<mesh
							geometry={nodes.sheep_head011.geometry}
							material={materials["food_d.011"]}
						/>
					</group>
					<group
						position={[-0.19, 0.55, -0.15]}
						rotation={[-0.02, 0.81, -1.51]}>
						<mesh
							geometry={nodes.sheep_head012.geometry}
							material={materials["food_d.012"]}
						/>
					</group>
					<group position={[-0.06, 0.66, -0.05]} rotation={[-0.19, 1.3, -1.33]}>
						<mesh
							geometry={nodes.sheep_head013.geometry}
							material={materials["food_d.013"]}
						/>
					</group>
					<group position={[-0.25, 0.66, -0.14]} rotation={[2.54, 1.08, 1.68]}>
						<mesh
							geometry={nodes.sheep_head014.geometry}
							material={materials["food_d.014"]}
						/>
					</group>
					<group position={[-0.2, 0.37, 0.08]} rotation={[-0.26, 0.05, 1.06]}>
						<mesh
							geometry={nodes.sheep_head015.geometry}
							material={materials["food_d.015"]}
						/>
					</group>
					<group position={[0.08, 0.49, 0.07]} rotation={[2.96, 0.43, -2.12]}>
						<mesh
							geometry={nodes.sheep_head002.geometry}
							material={materials["food_d.002"]}
						/>
					</group>
					<group position={[-0.08, 0.49, 0.11]} rotation={[-2.7, 1.32, -2.67]}>
						<mesh
							geometry={nodes.sheep_head003.geometry}
							material={materials["food_d.003"]}
						/>
					</group>
					<group position={[0.02, 0.64, 0.18]} rotation={[0.74, 1.51, -0.54]}>
						<mesh
							geometry={nodes.sheep_head004.geometry}
							material={materials["food_d.004"]}
						/>
					</group>
					<group position={[0.09, 0.56, 0.38]} rotation={[-3.13, 1.18, 1.43]}>
						<mesh
							geometry={nodes.sheep_head005.geometry}
							material={materials["food_d.005"]}
						/>
					</group>
					<group position={[0.35, 0.56, 0.12]} rotation={[-3.14, 0.21, 1.55]}>
						<mesh
							geometry={nodes.sheep_head006.geometry}
							material={materials["food_d.006"]}
						/>
					</group>
					<group position={[0.36, 0.55, -0.14]} rotation={[2.59, 0.68, 2.02]}>
						<mesh
							geometry={nodes.sheep_head007.geometry}
							material={materials["food_d.007"]}
						/>
					</group>
					<group position={[-0.28, 0.55, 0]} rotation={[0.06, -0.39, -1.39]}>
						<mesh
							geometry={nodes.sheep_head008.geometry}
							material={materials["food_d.008"]}
						/>
					</group>
					<group position={[-0.44, 0.5, -0.02]} rotation={[0.08, 0.31, -1.27]}>
						<mesh
							geometry={nodes.sheep_head009.geometry}
							material={materials["food_d.009"]}
						/>
					</group>
				</group>
				<group
					position={[-386.81, 149.12, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}
					scale={78}>
					<mesh
						geometry={nodes.mat_carpet_hFBXASC04613.geometry}
						material={materials.carpets_new_b}
					/>
				</group>
				<group
					position={[456.39, 1482.03, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Flowers002.geometry}
						material={materials.Meadowlark_flowers}
					/>
					<mesh
						geometry={nodes.Stems.geometry}
						material={materials["bark3.020"]}
					/>
				</group>
				<group
					position={[-828.09, -278.37, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.oakfall1001.geometry}
						material={materials["fallleaves.004"]}
					/>
				</group>
				<group
					position={[-756.57, 0.04, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.oakfall2001.geometry}
						material={materials["fallleaves.005"]}
					/>
				</group>
				<group
					position={[-372.5, 45.1, -1.22]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.oakfall2002.geometry}
						material={materials["fallleaves.013"]}
					/>
				</group>
				<group
					position={[-762.83, -60.89, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.oakfall2003.geometry}
						material={materials["fallleaves.014"]}
					/>
				</group>
				<group
					position={[-1744.95, 362.87, -4.13]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.leaves007.geometry}
						material={materials["HollyPrivet_Mat.004"]}
					/>
					<mesh
						geometry={nodes.stem.geometry}
						material={materials["bark3.006"]}
					/>
				</group>
				<group
					position={[-1781.91, -181.1, -34.23]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Rhododendron_branch.geometry}
						material={materials.TreeBark_1}
					/>
					<mesh
						geometry={nodes.Rhododendron_flower33.geometry}
						material={materials.Rhododendron}
					/>
					<mesh
						geometry={nodes.Rhododendron_branchjEI.geometry}
						material={materials.Rhododendron}
					/>
					<mesh
						geometry={nodes.Rhododendron_trunk.geometry}
						material={materials["TreeBark_01.002"]}
					/>
				</group>
				<group
					position={[-1524.19, -1004.63, -39.2]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_02M1.geometry}
						material={materials.Sycamore_leaf_v4_Mat2}
					/>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_0.geometry}
						material={materials.Sycamore_bark_Mat}
					/>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_0snf.geometry}
						material={materials.Sycamore_leaf_Mat2}
					/>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_0wdn.geometry}
						material={materials.Sycamore_leaf_v2_Mat2}
					/>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_0z0P.geometry}
						material={materials.Sycamore_leaf_v3_Mat2}
					/>
					<mesh
						geometry={nodes.Largebranch1.geometry}
						material={materials.Sycamore_bark_Mat}
					/>
					<mesh
						geometry={nodes.Largebranch2.geometry}
						material={materials.Sycamore_bark_Mat}
						position={[-1253.57, 169.95, 1257.35]}
						rotation={[2.29, -0.09, -2.62]}
						scale={1.5}
					/>
					<mesh
						geometry={nodes.Largebranch3.geometry}
						material={materials.Sycamore_bark_Mat}
						position={[-598.57, 258.75, -1021.67]}
						rotation={[1.31, 0.93, -0.73]}
						scale={1.1}
					/>
					<mesh
						geometry={nodes.trunk010.geometry}
						material={materials.sycamorebark2}
					/>
				</group>
				<group
					position={[-249.04, -2560.4, 306.29]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={
							nodes.Sycamore_branchShape_MASH1_Instancer_02M1001.geometry
						}
						material={materials["Sycamore_leaf_v4_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Sycamore_branchShape_MASH1_Instancer_0001.geometry}
						material={materials["Sycamore_bark_Mat.001"]}
					/>
					<mesh
						geometry={
							nodes.Sycamore_branchShape_MASH1_Instancer_0snf001.geometry
						}
						material={materials["Sycamore_leaf_Mat2.001"]}
					/>
					<mesh
						geometry={
							nodes.Sycamore_branchShape_MASH1_Instancer_0wdn001.geometry
						}
						material={materials["Sycamore_leaf_v2_Mat2.001"]}
					/>
					<mesh
						geometry={
							nodes.Sycamore_branchShape_MASH1_Instancer_0z0P001.geometry
						}
						material={materials["Sycamore_leaf_v3_Mat2.001"]}
					/>
					<mesh
						geometry={nodes.Largebranch1001.geometry}
						material={materials["Sycamore_bark_Mat.001"]}
					/>
					<mesh
						geometry={nodes.Largebranch2001.geometry}
						material={materials["Sycamore_bark_Mat.001"]}
						position={[-1253.57, 169.95, 1257.35]}
						rotation={[2.29, -0.09, -2.62]}
						scale={1.5}
					/>
					<mesh
						geometry={nodes.Largebranch3001.geometry}
						material={materials["Sycamore_bark_Mat.001"]}
						position={[-598.57, 258.75, -1021.67]}
						rotation={[1.31, 0.93, -0.73]}
						scale={1.1}
					/>
					<mesh
						geometry={nodes.trunk011.geometry}
						material={materials["sycamorebark2.001"]}
					/>
				</group>
				<group
					position={[-1640.77, -887.13, -29.22]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Thevetia_branch.geometry}
						material={materials.bark3_2}
					/>
					<mesh
						geometry={nodes.Thevetia_branchm4u.geometry}
						material={materials.Thevetia_leaves}
					/>
					<mesh
						geometry={nodes.Thevetia_flower26.geometry}
						material={materials.Thevetia_leaves}
					/>
					<mesh
						geometry={nodes.Thevetia_trunk.geometry}
						material={materials["bark3.005"]}
					/>
				</group>
				<group rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Yellow_Pine_Branch1.geometry}
						material={materials.Pine_bark}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch1jEI.geometry}
						material={materials["Pine_needles.002"]}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch2.geometry}
						material={materials.Pine_bark}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch2pR3.geometry}
						material={materials["Pine_needles.002"]}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch3.geometry}
						material={materials.Pine_bark}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch3wdn.geometry}
						material={materials["Pine_needles.002"]}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch42M1.geometry}
						material={materials["Pine_needles.002"]}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_Branch4.geometry}
						material={materials.Pine_bark}
					/>
					<mesh
						geometry={nodes.Yellow_Pine_trunk.geometry}
						material={materials.Pine_bark}
					/>
				</group>
				<group
					position={[-164.75, -885.81, 0]}
					rotation={[-Math.PI / 2, -1.57, 0]}>
					<mesh
						geometry={nodes.Pine_bark_Mat001.geometry}
						material={materials["TreeBark_10.001"]}
					/>
					<mesh
						geometry={nodes.Pine_needles_Mat001.geometry}
						material={materials["Pine_needles.001"]}
					/>
				</group>
				<mesh
					geometry={nodes.Plane.geometry}
					material={materials.Grass_Countryside}
					scale={1.11}
				/>
				<mesh
					geometry={nodes.Plane_01.geometry}
					material={materials.Grass_Countryside}
					position={[0, -109.51, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_02.geometry}
					material={materials.Grass_Countryside}
					position={[-855.72, -109.51, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_03.geometry}
					material={materials.Grass_Countryside}
					position={[0, -985.46, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_04.geometry}
					material={materials.Grass_Countryside}
					position={[-1011.1, -985.46, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_05.geometry}
					material={materials.Grass_Countryside}
					position={[623.82, -985.46, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_06.geometry}
					material={materials.Grass_Countryside}
					position={[623.82, -144.14, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_07.geometry}
					material={materials.Grass_Countryside}
					position={[-124.68, 815.43, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_08.geometry}
					material={materials.Grass_Countryside}
					position={[-1091.39, 797.87, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_09.geometry}
					material={materials.Grass_Countryside}
					position={[716.11, 823.53, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_10.geometry}
					material={materials.Grass_Countryside}
					position={[-124.68, 1653.83, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_11.geometry}
					material={materials.Grass_Countryside}
					position={[709.03, 1653.83, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_12.geometry}
					material={materials.Grass_Countryside}
					position={[-1819.25, -109.51, 0]}
					scale={10.12}
				/>
				<mesh
					geometry={nodes.Plane_13.geometry}
					material={materials.Grass_Countryside}
					position={[-1927.17, -985.46, 0]}
					scale={10.12}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/swamp.glb");
