/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export default function YonderSwitches({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"https://trickedex.app/yonderSwitches.gltf"
	);
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='DefaultScene'>
				<group name='World'>
					<group name='World_1'>
						<group name='defaultLight' rotation={[-Math.PI / 4, 0, 0]} />
						<group name='SphereLight' position={[-1.35, 3.85, 0.02]} />
						<group name='SphereLight_01' position={[-2.63, 3.88, -0.61]} />
						<group
							name='GswitchLOOP'
							position={[-2.62, -0.18, 0]}
							rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
							<group name='ManRoot'>
								<primitive object={nodes.RL_BoneRoot} />
							</group>
							<group name='LightRoot'>
								<group name='Key' rotation={[0.8, 0.65, 0.3]}>
									<group name='Key_1' />
								</group>
								<group name='Side' rotation={[-0.53, -1.21, -0.75]}>
									<group name='Side_1' />
								</group>
								<group name='Back' rotation={[-1.13, 0.28, 2.78]}>
									<group name='Back_1' position={[0.07, -0.3, -0.14]} />
								</group>
								<group name='Floor_Shadow' rotation={[0.67, -0.27, -0.5]}>
									<group name='Floor_Shadow_1' />
								</group>
							</group>
						</group>
						<group
							name='DistantLight'
							position={[-2.45, 0, 0]}
							rotation={[-2.81, 0.48, 1.41]}
						/>
						{/* <PerspectiveCamera
							name='Camera_1'
							makeDefault={false}
							far={10000}
							near={0.01}
							fov={63.09}
							position={[1.38, -5.46, 0.41]}
							rotation={[1.68, 0.43, -0.06]}
						/> */}
						{/* <PerspectiveCamera
							name='Camera_01_1'
							makeDefault={false}
							far={10000}
							near={0.01}
							fov={54.28}
							position={[-1.06, -1.13, 0.18]}
							rotation={[1.63, 0.58, -1.67]}
						/>
						<PerspectiveCamera
							name='Camera_02_1'
							makeDefault={false}
							far={10000}
							near={0.01}
							fov={54.28}
							position={[-0.66, -0.91, 0.35]}
							rotation={[1.54, 0.76, -1.53]}
						/> */}
					</group>
					<group name='Environment'>
						<group name='sky_moonlit_golf_4k' rotation={[-Math.PI / 2, 0, 0]} />
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/yonderSwitches.gltf");
