/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MyGLTF } from "types/mythree";

export default function SceneBackground({ ...props }) {
  const group = useRef<any>();
  const { nodes, materials } = useGLTF("/SceneBackground.glb") as MyGLTF;
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.32, 0.19, 0.93]} scale={0.99}>
        <pointLight intensity={0.6} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.17, 7.01, 4.26]} rotation={[1.03, -0.11, 0.02]}>
        <spotLight
          intensity={0.3}
          angle={0.2}
          penumbra={0.41}
          decay={2}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.66, 1.11, 0.49]}>
        <pointLight intensity={0.4} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[4.13, 0.65, 1.73]} rotation={[0.02, -0.26, -1.6]}>
        <spotLight
          intensity={0.8}
          angle={0.14}
          penumbra={0.67}
          decay={2}
          color="#1987ff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        geometry={nodes.Ground.geometry}
        material={materials["Material.004"]}
        scale={5}
      />
      <mesh
        geometry={nodes.TorqueWall.geometry}
        material={materials.TorqueWall}
        position={[0, 2, -5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[5, 1, 2]}
      />
      <mesh
        geometry={nodes.Wall.geometry}
        material={materials.BlueWall}
        position={[-5, 2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[2, 1, 5]}
      />
      <mesh
        geometry={nodes.TorqueWall002.geometry}
        material={materials["TorqueWall.002"]}
        position={[0, 2, 5]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[5, 1, 2]}
      />
      <mesh
        geometry={nodes.Wall002.geometry}
        material={materials["BlueWall.002"]}
        position={[5, 2, 0]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[2, 1, 5]}
      />
      <mesh
        geometry={nodes.TorqueWall001.geometry}
        material={materials["TorqueWall.001"]}
        position={[0, 2, -5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[5, 1, 2]}
      />
      <mesh
        geometry={nodes.Wall001.geometry}
        material={materials.YonderWall}
        position={[-5, 2, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[2, 1, 5]}
      />
    </group>
  );
}

// useGLTF.preload("/SceneBackground.glb");
