/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MyGLTF } from "types/mythree";

export default function SceneBackground({ ...props }) {
  const group = useRef<any>();
  const { nodes, materials } = useGLTF("/SceneBackground.glb") as MyGLTF;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Ground.geometry}
        material={materials["Material.004"]}
        scale={8}
      />
      <mesh
        geometry={nodes.TorqueWall.geometry}
        material={materials.TorqueWall}
        position={[0, 4, -8]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[8, 1, 4]}
      />

      <mesh
        geometry={nodes.TorqueWall002.geometry}
        material={materials["TorqueWall.002"]}
        position={[0, 4, 8]}
        rotation={[Math.PI / 2, 0, -Math.PI]}
        scale={[8, 1, 4]}
      />
      <mesh
        geometry={nodes.Wall002.geometry}
        material={materials.YonderWall}
        position={[8, 4, 0]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[8, 1, 4]}
      />

      <mesh
        geometry={nodes.Wall001.geometry}
        material={materials.YonderWall}
        position={[-8, 4, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[4, 1, 8]}
      />
    </group>
  );
}

// useGLTF.preload("/SceneBackground.glb");
