/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useStore } from "../store/store";
import * as THREE from "three";
import CC3 from "../data/AlexKerwood.gltf";

export default function Kerwood({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(CC3);
	const { actions, names, mixer } = useAnimations(animations, group);

	//Use Store
	const aI = useStore((s) => s.aI);
	const bounce = useStore((s) => s.bounce);
	const currentAnim = useStore((s) => s.currentAnim);
	const end = useStore((s) => s.end);
	const isPaused = useStore((s) => s.isPaused);
	const isPlaying = useStore((s) => s.isPlaying);
	const loop = useStore((s) => s.loop);
	const setAnimationsArray = useStore((s) => s.updateAnimationArray);
	const setClipDuration = useStore((s) => s.setClipDuration);
	const setCurrentTime = useStore((s) => s.setCurrentTime);
	const setSliderEnd = useStore((s) => s.setSliderEnd);
	const setSliderStart = useStore((s) => s.setSliderStart);
	const start = useStore((s) => s.start);
	const timescale = useStore((s) => s.timescale);
	const trimToggle = useStore((s) => s.trimToggle);

	//Solves Problem with infinte renders of Animations Array and successfully passes to store
	useMemo(
		() => Promise.resolve(names).then((results) => setAnimationsArray(results)),
		[names, setAnimationsArray]
	);

	//	Handle Animation Loop
	//bounce uE
	useEffect(() => {
		bounce
			? actions[currentAnim].setLoop(THREE.LoopPingPong)
			: actions[currentAnim].setLoop(THREE.LoopRepeat);
	}, [bounce, aI, actions, names, mixer, currentAnim]);

	//loop uE
	useEffect(() => {
		loop
			? actions[currentAnim].setLoop(THREE.LoopRepeat)
			: actions[currentAnim].setLoop(THREE.LoopOnce);
	}, [loop, aI, actions, names, mixer, currentAnim]);

	//Timescale (SlowMo, FullSpeed, Timeslider) uE
	useEffect(() => {
		actions[currentAnim].timeScale = timescale;
	}, [timescale, actions, mixer, currentAnim]);

	// Play Pause uE
	useEffect(() => {
		isPaused
			? (actions[currentAnim].timeScale = 0)
			: (actions[currentAnim].timeScale = timescale);
	}, [timescale, isPaused, aI, actions, names, currentAnim]);

	// Set Play Start uE
	useEffect(() => {
		isPlaying ? actions[currentAnim].play() : actions[currentAnim].play();
	}, [isPlaying, aI, actions, names, mixer, currentAnim, start, end]);

	useFrame(() => {
		if (!trimToggle) {
			const duration = parseFloat(
				actions[currentAnim].getClip().duration.toFixed(2)
			);
			let startHere = parseFloat((start * duration).toFixed(2));
			let endHere = parseFloat((end * duration).toFixed(2));
			let current = parseFloat(actions[currentAnim].time);

			if (current.toFixed(1) >= endHere.toFixed(1)) {
				actions[currentAnim].time = startHere;
			}
		}
		setCurrentTime(actions[currentAnim].time);
		setClipDuration(actions[currentAnim].getClip().duration);
	});

	//	Resets Animations Player on Change of CurrentAnim
	useEffect(() => {
		mixer.stopAllAction();
		actions[currentAnim].play();
	}, [currentAnim]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group scale={0.01}>
				<primitive object={nodes.pelvis} />
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_1'
					geometry={nodes.CC_Game_Body_1.geometry}
					material={materials.Ga_Skin_Body}
					skeleton={nodes.CC_Game_Body_1.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_1.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_1.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_2'
					geometry={nodes.CC_Game_Body_2.geometry}
					material={materials.Ga_Eyelash}
					skeleton={nodes.CC_Game_Body_2.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_2.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_2.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_3'
					geometry={nodes.CC_Game_Body_3.geometry}
					material={materials.Boxers}
					skeleton={nodes.CC_Game_Body_3.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_3.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_3.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_4'
					geometry={nodes.CC_Game_Body_4.geometry}
					material={materials.Jeans}
					skeleton={nodes.CC_Game_Body_4.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_4.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_4.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_5'
					geometry={nodes.CC_Game_Body_5.geometry}
					material={materials.Plaid_Punk_Shirt}
					skeleton={nodes.CC_Game_Body_5.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_5.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_5.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_6'
					geometry={nodes.CC_Game_Body_6.geometry}
					material={materials.Boots}
					skeleton={nodes.CC_Game_Body_6.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_6.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_6.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_7'
					geometry={nodes.CC_Game_Body_7.geometry}
					material={materials.Std_Upper_Teeth}
					skeleton={nodes.CC_Game_Body_7.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_7.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_7.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_8'
					geometry={nodes.CC_Game_Body_8.geometry}
					material={materials.Std_Lower_Teeth}
					skeleton={nodes.CC_Game_Body_8.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_8.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_8.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_9'
					geometry={nodes.CC_Game_Body_9.geometry}
					material={materials.Std_Eye_R}
					skeleton={nodes.CC_Game_Body_9.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_9.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_9.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_10'
					geometry={nodes.CC_Game_Body_10.geometry}
					material={materials.Std_Cornea_R}
					skeleton={nodes.CC_Game_Body_10.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_10.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_10.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_11'
					geometry={nodes.CC_Game_Body_11.geometry}
					material={materials.Std_Eye_L}
					skeleton={nodes.CC_Game_Body_11.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_11.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_11.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_12'
					geometry={nodes.CC_Game_Body_12.geometry}
					material={materials.Std_Cornea_L}
					skeleton={nodes.CC_Game_Body_12.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_12.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_12.morphTargetInfluences}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/AlexKerwood.gltf");
