/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useMemo, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useStore } from "../store/store";
import * as THREE from "three";
import CC3 from "../data/CC3Test.gltf";
import Kerwood from "../data/AlexKerwood.gltf";

export default function Model({ ...props }) {
	const group = useRef();
	// const { animations } = useGLTF(Kerwood);
	const { nodes, materials, animations } = useGLTF(CC3);
	const { actions, names, mixer } = useAnimations(animations, group);

	//Use Store
	const aI = useStore((s) => s.aI);
	const bounce = useStore((s) => s.bounce);
	const currentAnim = useStore((s) => s.currentAnim);
	const end = useStore((s) => s.end);
	const isPaused = useStore((s) => s.isPaused);
	const isPlaying = useStore((s) => s.isPlaying);
	const loop = useStore((s) => s.loop);
	const setAnimationsArray = useStore((s) => s.updateAnimationArray);
	const setClipDuration = useStore((s) => s.setClipDuration);
	const setCurrentTime = useStore((s) => s.setCurrentTime);
	const setSliderEnd = useStore((s) => s.setSliderEnd);
	const setSliderStart = useStore((s) => s.setSliderStart);
	const start = useStore((s) => s.start);
	const timescale = useStore((s) => s.timescale);
	const trimToggle = useStore((s) => s.trimToggle);

	//Solves Problem with infinte renders of Animations Array and successfully passes to store
	useMemo(
		() => Promise.resolve(names).then((results) => setAnimationsArray(results)),
		[names, setAnimationsArray]
	);

	//	Handle Animation Loop
	//	bounce uE
	useEffect(() => {
		bounce
			? actions[currentAnim].setLoop(THREE.LoopPingPong)
			: actions[currentAnim].setLoop(THREE.LoopRepeat);
	}, [bounce, aI, actions, names, mixer, currentAnim]);

	//loop uE
	useEffect(() => {
		loop
			? actions[currentAnim].setLoop(THREE.LoopRepeat)
			: actions[currentAnim].setLoop(THREE.LoopOnce);
	}, [loop, aI, actions, names, mixer, currentAnim]);

	//Timescale (SlowMo, FullSpeed, Timeslider) uE
	useEffect(() => {
		actions[currentAnim].timeScale = timescale;
	}, [timescale, actions, mixer, currentAnim]);

	// Play Pause uE
	useEffect(() => {
		isPaused
			? (actions[currentAnim].timeScale = 0)
			: (actions[currentAnim].timeScale = timescale);
	}, [timescale, isPaused, aI, actions, names, currentAnim]);

	// Set Play Start uE
	useEffect(() => {
		isPlaying ? actions[currentAnim].play() : actions[currentAnim].play();
	}, [isPlaying, aI, actions, names, mixer, currentAnim, start, end]);

	useFrame(() => {
		if (!trimToggle) {
			const duration = parseFloat(
				actions[currentAnim].getClip().duration.toFixed(2)
			);
			let startHere = parseFloat((start * duration).toFixed(2));
			let endHere = parseFloat((end * duration).toFixed(2));
			let current = parseFloat(actions[currentAnim].time);

			if (current.toFixed(1) >= endHere.toFixed(1)) {
				actions[currentAnim].time = startHere;
			}
		}
		setCurrentTime(actions[currentAnim].time);
		setClipDuration(actions[currentAnim].getClip().duration);
	});

	//	Resets Animations Player on Change of CurrentAnim
	useEffect(() => {
		mixer.stopAllAction();
		actions[currentAnim].play();
	}, [currentAnim]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group scale={0.01}>
				<primitive object={nodes.pelvis} />
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Air_Jordan_3obj_1.geometry}
					material={materials.Shoe_Left}
					skeleton={nodes.Air_Jordan_3obj_1.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Air_Jordan_3obj_2.geometry}
					material={materials.Shoe_Right}
					skeleton={nodes.Air_Jordan_3obj_2.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Eye_1.geometry}
					material={materials.Std_Eye_R}
					skeleton={nodes.CC_Base_Eye_1.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Eye_2.geometry}
					material={materials.Std_Cornea_R}
					skeleton={nodes.CC_Base_Eye_2.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Eye_3.geometry}
					material={materials.Std_Eye_L}
					skeleton={nodes.CC_Base_Eye_3.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Eye_4.geometry}
					material={materials.Std_Cornea_L}
					skeleton={nodes.CC_Base_Eye_4.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Teeth_1.geometry}
					material={materials.Std_Upper_Teeth}
					skeleton={nodes.CC_Base_Teeth_1.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.CC_Base_Teeth_2.geometry}
					material={materials.Std_Lower_Teeth}
					skeleton={nodes.CC_Base_Teeth_2.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Chin_Curtain_Sparse.geometry}
					material={materials.Beard}
					skeleton={nodes.Chin_Curtain_Sparse.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Jeans.geometry}
					material={materials.Jeans}
					skeleton={nodes.Jeans.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Mustache_Horseshoe.geometry}
					material={materials["Beard.002"]}
					skeleton={nodes.Mustache_Horseshoe.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Object021_0_1.geometry}
					material={materials.Scalp_High_polytail}
					skeleton={nodes.Object021_0_1.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Object021_0_2.geometry}
					material={materials.High_polytail}
					skeleton={nodes.Object021_0_2.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Plaid_Punk_Shirt.geometry}
					material={materials.Plaid_Punk_Shirt}
					skeleton={nodes.Plaid_Punk_Shirt.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Stubble_Neck.geometry}
					material={materials["Beard.001"]}
					skeleton={nodes.Stubble_Neck.skeleton}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_1'
					geometry={nodes.CC_Game_Body_1.geometry}
					material={nodes.CC_Game_Body_1.material}
					skeleton={nodes.CC_Game_Body_1.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_1.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_1.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Body_2'
					geometry={nodes.CC_Game_Body_2.geometry}
					material={materials.Ga_Eyelash}
					skeleton={nodes.CC_Game_Body_2.skeleton}
					morphTargetDictionary={nodes.CC_Game_Body_2.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Body_2.morphTargetInfluences}
				/>
				<skinnedMesh
					frustumCulled={false}
					name='CC_Game_Tongue'
					geometry={nodes.CC_Game_Tongue.geometry}
					material={nodes.CC_Game_Tongue.material}
					skeleton={nodes.CC_Game_Tongue.skeleton}
					morphTargetDictionary={nodes.CC_Game_Tongue.morphTargetDictionary}
					morphTargetInfluences={nodes.CC_Game_Tongue.morphTargetInfluences}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/CC3Test.gltf");
