/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useMemo } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useStore } from "../store/store";
import * as THREE from "three";

export function Frank({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("/Frank.gltf");
	const { actions, names, mixer } = useAnimations(animations, group);

	//Use Store
	const aI = useStore((state) => state.aI);
	let isPlaying = useStore((state) => state.isPlaying);
	let isPaused = useStore((state) => state.isPaused);
	const setAnimationsArray = useStore((state) => state.updateAnimationArray);
	const timescale = useStore((state) => state.timescale);
	const loop = useStore((state) => state.loop);
	const bounce = useStore((state) => state.bounce);
	const currentAnim = useStore((state) => state.currentAnim);
	const start = useStore((state) => state.start);
	const end = useStore((state) => state.end);
	//Solves Problem with infinte renders of Animations Array and successfully passes to store
	useMemo(
		() => Promise.resolve(names).then((results) => setAnimationsArray(results)),
		[names, setAnimationsArray]
	);

	// Handle Animation Loop

	useEffect(() => {
		bounce
			? actions[currentAnim].setLoop(THREE.LoopPingPong)
			: actions[currentAnim].setLoop(THREE.LoopRepeat);
	}, [bounce, aI, actions, names, mixer, currentAnim]);
	useEffect(() => {
		loop
			? actions[currentAnim].setLoop(THREE.LoopRepeat)
			: actions[currentAnim].setLoop(THREE.LoopOnce);
	}, [loop, aI, actions, names, mixer, currentAnim]);
	useEffect(() => {
		actions[currentAnim].timeScale = timescale;
	}, [timescale, actions, mixer, currentAnim]);
	useEffect(() => {
		const duration = actions[currentAnim].getClip().duration;
		const startHere = start * duration;
		isPlaying
			? actions[currentAnim].startAt(startHere)
			: actions[currentAnim].halt();
	}, [isPlaying, aI, actions, names, mixer, currentAnim, start]);
	useEffect(() => {
		isPaused
			? (actions[currentAnim].timeScale = 0)
			: (actions[currentAnim].timeScale = timescale);
	}, [timescale, isPaused, aI, actions, names, currentAnim]);
	// useEffect(() => {
	// 	const duration = actions[currentAnim].getClip().duration;
	// 	const startHere = start * duration;
	// 	const endHere = end * duration;
	// 	actions[currentAnim].getClip().trim(startHere, endHere);
	// 	console.log("newTime", endHere - startHere);
	// 	console.log("startHere", startHere);
	// 	console.log("endHere", endHere);

	// 	console.log("time", actions[currentAnim].time);
	// 	console.log("duration", actions[currentAnim].getClip().duration);

	// 	console.log("div", end - start);
	// }, [start, end, currentAnim]);

	useEffect(() => {
		mixer.stopAllAction();
	}, [currentAnim]);
	useEffect(() => {
		const duration = actions[currentAnim].getClip().duration;
		const startHere = start * duration;
		console.log("startHere", startHere);
		actions[currentAnim].startAt(startHere).play();
	}, [currentAnim, start]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
				<primitive object={nodes.mixamorig1Hips} />
				<skinnedMesh
					frustumCulled={false}
					geometry={nodes.Skin.geometry}
					material={materials.Ch36_Body}
					skeleton={nodes.Skin.skeleton}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/Frank.gltf");
