/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import KerwoodFBX from "../data/KerwoodCC3Tpose.gltf";
import { AlphaFormat, SubtractiveBlending } from "three";

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(KerwoodFBX);
	const { actions } = useAnimations(animations, group);
	return (
		<group ref={group} {...props} dispose={null}>
			<group scale={0.01}>
				<primitive frustumCulled={false} object={nodes.BoneRoot} />
				<skinnedMesh
					geometry={nodes.CC_Base_Body_1.geometry}
					material={materials.Std_Skin_Head}
					skeleton={nodes.CC_Base_Body_1.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Body_2.geometry}
					material={materials.Std_Skin_Body}
					skeleton={nodes.CC_Base_Body_2.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Body_3.geometry}
					material={materials.Std_Skin_Arm}
					skeleton={nodes.CC_Base_Body_3.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Body_4.geometry}
					material={materials.Std_Skin_Leg}
					skeleton={nodes.CC_Base_Body_4.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Body_5.geometry}
					material={materials.Std_Nails}
					skeleton={nodes.CC_Base_Body_5.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Body_6.geometry}
					material={materials.Std_Eyelash}
					skeleton={nodes.CC_Base_Body_6.skeleton}
					frustumCulled={false}
					visible={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_TearLine_1.geometry}
					material={materials.Std_Tearline_R}
					skeleton={nodes.CC_Base_TearLine_1.skeleton}
					frustumCulled={false}
					visible={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_TearLine_2.geometry}
					material={materials.Std_Tearline_L}
					skeleton={nodes.CC_Base_TearLine_2.skeleton}
					frustumCulled={false}
					visible={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_EyeOcclusion_1.geometry}
					material={materials.Std_Eye_Occlusion_R}
					skeleton={nodes.CC_Base_EyeOcclusion_1.skeleton}
					frustumCulled={false}
					visible={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_EyeOcclusion_2.geometry}
					material={materials.Std_Eye_Occlusion_L}
					skeleton={nodes.CC_Base_EyeOcclusion_2.skeleton}
					frustumCulled={false}
					visible={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Tongue.geometry}
					material={materials.Std_Tongue}
					skeleton={nodes.CC_Base_Tongue.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.Boots.geometry}
					material={materials.Boots}
					skeleton={nodes.Boots.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.Boxers.geometry}
					material={materials.Boxers}
					skeleton={nodes.Boxers.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Eye_1.geometry}
					material={materials.Std_Eye_R}
					skeleton={nodes.CC_Base_Eye_1.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Eye_2.geometry}
					material={materials.Std_Cornea_R}
					skeleton={nodes.CC_Base_Eye_2.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Eye_3.geometry}
					material={materials.Std_Eye_L}
					skeleton={nodes.CC_Base_Eye_3.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Eye_4.geometry}
					material={materials.Std_Cornea_L}
					skeleton={nodes.CC_Base_Eye_4.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Teeth_1.geometry}
					material={materials.Std_Upper_Teeth}
					skeleton={nodes.CC_Base_Teeth_1.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.CC_Base_Teeth_2.geometry}
					material={materials.Std_Lower_Teeth}
					skeleton={nodes.CC_Base_Teeth_2.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.Jeans.geometry}
					material={materials.Jeans}
					skeleton={nodes.Jeans.skeleton}
					frustumCulled={false}
				/>
				<skinnedMesh
					geometry={nodes.Plaid_Punk_Shirt.geometry}
					material={materials.Plaid_Punk_Shirt}
					skeleton={nodes.Plaid_Punk_Shirt.skeleton}
					frustumCulled={false}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(KerwoodFBX);
