/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
useGLTF.preload("https://trickedex.app/torqueLogo.gltf");

export default function TorqueLogo(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"https://trickedex.app/torqueLogo.gltf"
	);
	const { actions } = useAnimations(animations, group);

	//Logic for playing animation
	const [isPlaying, setIsPlaying] = useState(false);
	const handleIsPlaying = () => setIsPlaying(!isPlaying);
	if (actions.Spin !== undefined) {
		isPlaying ? actions.Spin.play() : actions.Spin.stop();
	}
	//Torque Logo Model
	return (
		<group ref={group} {...props} dispose={null}>
			<mesh
				onClick={handleIsPlaying}
				name='Torque_Logo_3d'
				geometry={nodes.Torque_Logo_3d.geometry}
				material={materials.SVGMat}
			/>
		</group>
	);
}
