/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
useGLTF.preload('../AnimatingTest.gltf')

export function Fred (props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../AnimatingTest.gltf')
  const { actions } = useAnimations(animations, group)

  if (actions.BKick !== undefined){
  let animations = [actions.BKick, actions.Backflip];
  let index = 1;
  animations[index].play();
  props.playing ? animations[index].timeScale = 1 : animations[index].timeScale = 0;
  console.log(actions);
}

    return (
    <group  ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive  object={nodes.mixamorig1Hips} />
        <skinnedMesh 

        geometry={nodes.Fred.geometry} 
        material={materials.Fred} 
        skeleton={nodes.Fred.skeleton} />
      
      </group>
    </group>
  )
}

 