/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../torqueLogo.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh scale={4} name="Torque_Logo_3d" geometry={nodes.Torque_Logo_3d.geometry} material={materials.SVGMat}/>
    
    </group>
  )
}

useGLTF.preload('../torqueLogo.gltf')
 