/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
useGLTF.preload('../torqueLogo.gltf')

export default function TorqueLogo(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('../torqueLogo.gltf')
  const { actions } = useAnimations(animations, group)  
  const [isPlaying, setIsPlaying] = useState(false);
  const handleIsPlaying = () => setIsPlaying(!isPlaying);
  if (actions.Spin !== undefined) {
    isPlaying ? actions.Spin.play() : actions.Spin.stop();
  }   
  
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh onClick={handleIsPlaying} name="Torque_Logo_3d" geometry={nodes.Torque_Logo_3d.geometry} material={materials.SVGMat}/>
       
      
    
    </group>
  )
}

 