/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { MyGLTF } from "types/mythree";

export default function BluesBackground({ ...props }) {
  const group = useRef<any>();
  const { nodes, materials } = useGLTF("/1st_scene.glb") as MyGLTF;
  return (
    <group
      scale={3}
      position={[-10, 0, -10]}
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <group
          name="Sketchfab_model"
          position={[0, -7.48, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="Low_Poly_Sealifeobjcleanermaterialmergergles">
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials.Seabed}
              position={[0, 0, 4.39]}
            />
            <mesh
              name="Object_5"
              geometry={nodes.Object_5.geometry}
              material={materials.Stones}
              position={[0, 0, 4.14]}
            />
            <mesh
              name="Object_6"
              geometry={nodes.Object_6.geometry}
              material={materials.fish}
              position={[0, 3.68, 4.51]}
            />
            <mesh
              name="Object_7"
              geometry={nodes.Object_7.geometry}
              material={materials["fish-1233608"]}
              position={[0, 3.68, 4.51]}
            />
            <mesh
              name="Object_11"
              geometry={nodes.Object_11.geometry}
              material={materials.plant1}
              position={[0, 0, 3.53]}
            />
            <mesh
              name="Object_12"
              geometry={nodes.Object_12.geometry}
              material={materials.plant2}
              position={[0, 0, 3.63]}
            />
            <mesh
              name="Object_13"
              geometry={nodes.Object_13.geometry}
              material={materials.plant3}
              position={[0, 0, 3.81]}
            />
            <mesh
              name="Object_14"
              geometry={nodes.Object_14.geometry}
              material={materials.veins}
              position={[0, 0, 3.63]}
            />
            <mesh
              name="Object_3"
              geometry={nodes.Object_3.geometry}
              material={materials["waterbody-248426379"]}
            />
            <mesh
              name="Object_8"
              geometry={nodes.Object_8.geometry}
              material={materials.fish2}
            />
            <mesh
              name="Object_9"
              geometry={nodes.Object_9.geometry}
              material={materials["fish2-825579"]}
            />
          </group>
        </group>
        <mesh
          name="Ground"
          geometry={nodes.Ground.geometry}
          material={materials["Material.004"]}
          scale={5}
        />
      </group>
    </group>
  );
}

// useGLTF.preload("/1st_scene.glb");
