name: Build Trickedex
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PNPM Setup
        uses: pnpm/action-setup@v2
        with:
          version: "6.14.1"

      - name: Cache Stuff
        uses: actions/cache@v3
        with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
  # If source files changed but packages didn't, rebuild from a prior cache.
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: setup Env file from github secret
        shell: bash
        working-directory: ./frontend
        run: |
          echo -e "${{secrets.env_file}}" > .env
          echo "Setup env file successfully"

      - name: Build
        run: pnpm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "unnecessary"

      - name: Adding Known Hosts
        run: ssh-keyscan -H "trickedex.app" >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . root@trickedex.app:/root/tricking-3d-tester

  # Add more jobs or steps as needed
