name: Build Trickedex
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PNPM Setup
        uses: pnpm/action-setup@v2
        with:
          version: "6.14.1"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: setup Env file from github secret
        shell: bash
        run: |
          echo -e "${{secrets.env_file}}" > .env
          echo "Setup env file successfully"

      - name: Build
        run: pnpm run build

      - name: Additional Step
        run: echo "This is an additional step"

  # Add more jobs or steps as needed
