name: Test ENV
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: setup Env file from github secret
        shell: bash
        run: |
          echo -e "${{secrets.env_file}}" > .env
          echo "Setup was a success"
          ls -R

      - name: SSH to Server
        uses: appleboy/ssh-action@master
        with:
          host: "trickedex.app"
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd tricking-3d
            sudo ln -s "/root/.nvm/versions/node/v16.18.1/bin/node" "/usr/local/bin/node" || true
            sudo ln -s "/root/.nvm/versions/node/v16.18.1/bin/pnpm" "/usr/local/bin/pnpm" || true
            sudo ln -s "$/root/.local/share/pnpm/pm2" "/usr/local/bin/pm2"  || true
            pnpm i
            pm2 restart all
            echo "Deployed Successfully"
